version: 2
jobs:
  build:
    working_directory: ~/parr
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9
    steps:
      - run:
          name: Fix host authenticity for DEPLOY_HOST
          command: |
            mkdir ~/.ssh; \
            ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
      - run:
          name: Deploy to EC2
          command: |
            ssh $DEPLOY_USER@$DEPLOY_HOST '\
              cd ~/parr && git fetch origin master && \
              git reset --hard origin/master && \
              bash scripts/deploy.sh \
            '
    branches:
      only:
        - master
